"""add local users

Revision ID: cb2b1056a393
Revises: 7eb2e3273c5e
Create Date: 2026-07-18 22:12:09.432031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb2b1056a393'
down_revision = '7eb2e3273c5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        pass  # Si borraste la línea, pon 'pass' para que no quede el bloque vacío

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_users_email', type_='unique')

    # ### end Alembic commands ###
